build.rs: Use pkg-config to find header search paths for bindgen.
stratis-storage/libblkid-rs pull request #171
Opened 2024-11-20 23:17 UTC by francis-starlab

This optionally enables using pkg-config to find header search paths and linker paths.  The pkg-config crate prints "cargo:rustc-link-lib=blkid" along with the appropriate library search paths. 

Additionally this adds an option static feature for statically linking libblkid.

2024-11-25 21:17 UTC, mulkieran commented on libblkid-rs-sys/Cargo.toml
> +pkg-config = []
Please remove empty line.

2024-11-25 21:19 UTC, mulkieran commented
@jbaublitz Could you take a look at this?

2024-11-26 16:22 UTC, jbaublitz commented
@francis-starlab Hi, thanks for the contribution! Could you explain a little bit more what your use case is here or the problem that you're running into that this resolves?

From what I can tell, one thing you want is static compilation. Is that correct?

For the include flags, can you explain a bit more what the problem is you're bumping into with the lack of using pkg-config to provide the include flags?

I basically want to have a better understanding of whether these changes should be the default and will benefit all of our users.

2024-11-27 16:56 UTC, francis-starlab commented
> Could you explain a little bit more what your use case is here or the problem that you're running into that this resolves?

We are cross compiling internal rust (and c and c++) in an environment with non-standard header locations. It's generally more convenient/consistent with other code for us to use pkg-config to provide header/linker paths. Otherwise we can use build.rs and various bindgen env vars, so this is mostly just to simplify things. We also link thinks statically, so that's also for helping simplify things for us.

2024-12-02 16:32 UTC, jbaublitz commented
> > Could you explain a little bit more what your use case is here or the problem that you're running into that this resolves?
> 
> We are cross compiling internal rust (and c and c++) in an environment with non-standard header locations. It's generally more convenient/consistent with other code for us to use pkg-config to provide header/linker paths. Otherwise we can use build.rs and various bindgen env vars, so this is mostly just to simplify things. We also link thinks statically, so that's also for helping simplify things for us.

Are you currently using the env var for bindgen to enable these currently? If so, I think it's worth taking this PR and generalizing it to all of our bindings to ease this use case for all of them.

2024-12-02 21:47 UTC, francis-starlab commented
>Are you currently using the env var for bindgen to enable these currently? 

Currently we are using a forked  libblkid-rs, though prior to that we where using `BINDGEN_EXTRA_CLANG_ARGS` to pass header paths. 

>If so, I think it's worth taking this PR and generalizing it to all of our bindings to ease this use case for all of them. 

I assume we are talking about the following?

https://github.com/stratis-storage/libcryptsetup-rs/tree/master/libcryptsetup-rs-sys 
https://github.com/stratis-storage/devicemapper-rs

I can most likely make similary such PRs against those if desired.

2024-12-03 15:07 UTC, jbaublitz commented
Yes, that would be great, thanks! I'm going to try to get to review today of this PR and then we can move on to the other bindings.

2024-12-03 19:18 UTC, jbaublitz requested changes
I'll merge it after you make this change and then if you're willing to put up something similar for the other bindings, that would be wonderful. Thanks for your contribution!

2024-12-11 22:15 UTC, francis-starlab commented on libblkid-rs-sys/build.rs
> +        }
Sorry for the slow response. I have updated the PR to make the pkg-config code path the only one.

2024-12-11 22:17 UTC, francis-starlab commented
I have made a similar/equivalent PR for devicemapper-rs here: https://github.com/stratis-storage/devicemapper-rs/pull/952

https://github.com/stratis-storage/libcryptsetup-rs already uses pkg-config and therefore needs no such MR.

2024-12-16 22:18 UTC, jbaublitz commented
@francis-starlab Could you make one more PR for libcryptsetup-rs?

2024-12-16 22:19 UTC, jbaublitz approved these changes
I'm happy to do the rebasing and merging if you're okay with it @francis-starlab. Any objection to merging this @mulkieran?

2024-12-16 23:58 UTC, mulkieran commented
@francis-starlab Can you rebase, please?

2024-12-16 23:58 UTC, mulkieran approved these changes

2024-12-18 18:37 UTC, francis-starlab commented
> @francis-starlab It appears I can't rebase this PR because of some setting not letting me update your repository like I have been able to with other external contributors. If you rebase, I'll immediately merge.

rebased.

2024-12-18 19:08 UTC, merged